# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c7543d3e-ffe2-46a9-853e-250fb65ad1d8'
  imageRepository: 'mobijajuacedocker'
  containerRegistry: 'acerg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/experimental/ace-minimal-install/Dockerfile.alpine'
  tag: '$(Build.BuildId)'



stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
